"$schema" = "./node_modules/wrangler/config-schema.json"
name = "private-archive-e2e-db"
main = "src/worker/index.ts"
compatibility_date = "2026-08-11"

[[d1_databases]]
binding = "DB"
database_name = "private-archive-db"
database_id = "8ca60403-dd2b-48fa-8e07-9b0274a258fc"
migrations_dir = "migrations"
